#!/bin/sh /etc/rc.common

# This is a misnomer; we won't run dnsmasq. We did setup of the "WAN" interface to 203.0.113.1/24
# in S20network. If there IS no WAN interface, we did nothing and you need to find out the IP
# the router got from DHCP (S20network). -wusel, 20150405

SETUP_MODE_DHCP_RANGE=203.0.113.2,203.0.113.254
SETUP_MODE_ADDR=203.0.113.1
SETUP_MODE_NETMASK=255.255.255.0

START=60

USE_PROCD=0
PROG=/usr/sbin/dnsmasq


start_service() {
#	procd_open_instance
#	procd_set_param command $PROG -k -p 0 -F $SETUP_MODE_DHCP_RANGE -l /tmp/dhcp.leases -O option:router
#	procd_set_param respawn
#	procd_close_instance
}
